---
title: "Lab5"
author: "Andrew Muehr"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

## Task 1

```{r}
getwd()
```

## Task 2

```{r}
## sampling function
# iter = iterations, n=sample size
# set default values
mybin=function(iter=100,n=10, p=0.7){ 
# make a matrix to hold the samples
#initially filled with NA's
#p1 = as.character(p)
sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
#Make a vector to hold the number of successes in each trial
succ=c()
for( i in 1:iter){
#Fill each column with a new sample
sam.mat[,i]=sample(c(1,0),n,replace=TRUE, prob=c(p,1-p))
#Calculate a statistic from the sample (this case it is the sum)
succ[i]=sum(sam.mat[,i])
}
#Make a table of successes
succ.tab=table(factor(succ,levels=0:n))
#Make a barplot of the proportion
barplot(succ.tab/(iter), col=rainbow(n+1), main="Binomial Simulation", sub=(iter), xlab="Number of successes")
succ.tab/iter
}
mybin(iter=100,n=10,p=0.7)
mybin(iter=200,n=10,p=0.7)
mybin(iter=500,n=10,p=0.7)
mybin(iter=1000,n=10, p=0.7)
mybin(iter=10000,n=10,p=0.7)

"Table for 10000 iterations: 0.0000 0.0002 0.0020 0.0093 0.0416 0.1013 0.1958 0.2707 0.2355 0.1185 0.0251"

vec = c(0:10)

dbinom(vec,10,0.7)

"The values produced from dbinom() match up well with those produced in the binomial simulations"
```

## Task 3

```{r}
sample(rep(c("1","0"), c(12,8)), size=5, replace=FALSE)

sample(rep(c("1","0"), c(12,8)), size=5,replace=TRUE)


myhyper=function(iter=100,N=20,r=12,n=5){
# make a matrix to hold the samples
#initially filled with NA's
sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
#Make a vector to hold the number of successes over the trials
succ=c()
for( i in 1:iter){
#Fill each column with a new sample
sam.mat[,i]=sample(rep(c(1,0),c(r,N-r)),n,replace=FALSE)
#Calculate a statistic from the sample (this case it is the sum)
succ[i]=sum(sam.mat[,i])
}
#Make a table of successes
succ.tab=table(factor(succ,levels=0:n))
#Make a barplot of the proportions
barplot(succ.tab/(iter), col=rainbow(n+1), main="HYPERGEOMETRIC simulation", xlab="Number of successes")
succ.tab/iter
}
#myhyper(iter=100,n=5, N=20,r=12)
#myhyper(iter=250,n=5, N=20,r=12)
#myhyper(iter=500,n=5, N=20,r=12)
#myhyper(iter=1000,n=5, N=20,r=12)
myhyper(iter=10000,n=5, N=20,r=12)

"This is the table from the 10000 iterations ismulation: 

     0      1      2      3      4      5 
0.0039 0.0505 0.2379 0.4018 0.2561 0.0498 "

dhyper(x=0:5, m=12, n=8, k=5)

"dhyper produces expected values that are within 0.005 of each value produced in the 10000 iteration simulation. Thus, the values in the table are very accurate."

```

## Task 4

```{r}
"I think that the mysample() function should take a sample of 1 through 10 (with replacemnt), and create a barplot of the outcome."

mysample=function(n, iter=10,time=0.5){
for( i in 1:iter){
#make a sample
s=sample(1:10,n,replace=TRUE)
# turn the sample into a factor
sf=factor(s,levels=1:10)
#make a barplot
barplot(table(sf)/n,beside=TRUE,col=rainbow(10), 
main=paste("Example sample()", " iteration ", i, " n= ", n,sep="") ,
ylim=c(0,0.2)
)

#release the table
Sys.sleep(time)
}
}

mysample(n=1000, iter=30)
```

## Task 5

```{r}
choose(8,4)

1-ppois(4,2)

#P(Y=10), Y~NegBin(p=0.4,r=3).   (Book theory)
#  This means that in R we need n=3 (size), x=y-r=10-3=7
dnbinom(7,3,0.4)  # Nu Failures, Nu of successes, prob success
mynbin=function(y,r,p){
choose(y-1,r-1)*p^r*(1-p)^(y-r)
}
mynbin(10,3,0.4)

pbinom(8,15,0.4)

```

## Task 6

```{r}
#library(MATH4753) # For some reason the html file cannot find this package...

#mynbin(10,3,0.5)

#ILAS2019::mybin(10,3,0.5)  ## Package not found

```
